### PR TITLE
Fontification: smoked out corner cases

### PR DESCRIPTION
**Pull request by ljli**
Some testing paid off.

### CODE REVIEW

**Comment by matthewbauer** [comment]
Looks like good changes! The complexity of your previous changes scared me but I like this. Eventually I'm going to add unit tests hopefully.

**Comment by matthewbauer** [comment]
Ok so I'm getting some issues on line 185 of all-packages.nix. 

```
    baseUrl = "https://github.com/${owner}/${repo}";
```

It seems to be that the combo of ```}"``` is messing things up. Adding a space after the ```}``` gets rid of the issue.


```
    baseUrl = "https://github.com/${owner}/${repo} ";
```

**Comment by ljli** [comment]
What exactly is the problem? Works fine for me, although for me it's line 190 on current nixpkgs head.

**Comment by matthewbauer** [comment]
Interesting... For me it's turning all of the following lines into strings:

screen shot 2017-03-28 at 8 12 20 pm

GNU Emacs 25.1.2 (x86_64-apple-darwin16.3.0, Carbon Version 157 AppKit 1504.76)

**Comment by ljli** [comment]
Ok, my guess is cross pollution between different nix-modes. Specifically the syntax-table. I bet the " before everthing turns string is in the character class ", which it shouldn't be since I gave it punctuation instead (that is .).
This could help:
(makunbound 'nix-mode-syntax-table)
eval-defun on nix-mode-syntax-table
(nix-mode) in all-packages.nix

**Comment by matthewbauer** [comment]
Awesome! that works for me. Is it okay for me to merge this into master?

**Comment by ljli** [comment]
Please do, I think it's mature if that's what you mean.

**Pull request merged**
